# NUMPY

In [1]:
import numpy

In [2]:
numpy.array([1, 2, 3])

array([1, 2, 3])

In [3]:
numpy.array([10, 20, 30, 40])

array([10, 20, 30, 40])

In [4]:
import numpy as np

In [5]:
np.array([2, 4, 6, 8])

array([2, 4, 6, 8])

In [6]:
a = np.array([2, 4, 6, 8])
a

array([2, 4, 6, 8])

In [7]:
np.array(["yogesh", "rajesh"])   #  note - numpy stand for numeric data not for string only numerical data is acquire

array(['yogesh', 'rajesh'], dtype='<U6')

In [10]:
np.array([True, False, "Raju", "Shiva", 76, 8.45, 34])    #  in numpy we can take integer and float data

array(['True', 'False', 'Raju', 'Shiva', '76', '8.45', '34'], dtype='<U32')

In [8]:
b = np.array([10, 20, 30, 40, 50])

In [9]:
b

array([10, 20, 30, 40, 50])

In [11]:
c = np.array([23, 54, 67, 54, 76])
c

array([23, 54, 67, 54, 76])

In [22]:
a = np.array([10, 20, 30, 40])
a

array([10, 20, 30, 40])

In [23]:
a.size   # total no of elements present inside of this array

4

In [16]:
c.size   # how much element are present inside this array we can find this for size

5

In [17]:
c.dtype    # this is show data type

dtype('int32')

In [24]:
a.dtype

dtype('int32')

In [19]:
b.dtype

dtype('int32')

8 bit = 1 byte
in above code 32 bit are their it means 4 bytes are their

In [25]:
a.itemsize  # how many items are their, how many byte are their

4

In [36]:
d = np.array([45, 44, 23, 65], dtype = 'int32')
d

array([45, 44, 23, 65])

In [37]:
d.itemsize   # 4 bytes are present inside d

4

In [38]:
d.min()

23

In [39]:
d.max()

65

In [44]:
x = np.array([100, 200, 300, 400, 500, 600, 700], dtype='int32')
x

array([100, 200, 300, 400, 500, 600, 700])

In [45]:
x.dtype

dtype('int32')

In [46]:
x.size

7

In [47]:
x.itemsize

4

In [49]:
y = np.array([12, 67, 89, 34, 45, 22], dtype='float')
y

array([12., 67., 89., 34., 45., 22.])

In [50]:
y.dtype

dtype('float64')

In [51]:
y.size

6

In [52]:
y.itemsize

8

2-D Dimension array data

In [53]:
p = np.array([[1,2],[3,4]])

In [54]:
p

array([[1, 2],
       [3, 4]])

In [100]:
p.ndim    # ndim means no of dimensions

2

In [55]:
p.dtype

dtype('int32')

In [56]:
p.itemsize

4

In [57]:
p.size

4

In [58]:
p.shape   # shape is show rows and columns here 2 rows and 2 columns

(2, 2)

In [59]:
p.min()

1

In [60]:
p.max()

4

In [61]:
type(p)   # it is show p is a numpy multi dimension array data

numpy.ndarray

In [62]:
m = np.array([[10,20,30],[40,50,60]])
m

array([[10, 20, 30],
       [40, 50, 60]])

In [101]:
m.ndim

2

In [63]:
m.shape

(2, 3)

In [102]:
k = np.array([[23,54],[54,67],[23,98]])
k

array([[23, 54],
       [54, 67],
       [23, 98]])

In [103]:
k.ndim

2

In [70]:
k.shape

(3, 2)

In [71]:
k.min()

23

In [72]:
k.max()

98

In [73]:
k.itemsize

4

In [75]:
k.size

6

In [76]:
k[0]

array([23, 54])

In [77]:
k[1]

array([54, 67])

In [78]:
k[-1]

array([23, 98])

In [79]:
s = np.array([[34,56,78],[87,65,43],[55,77,33]])
s

array([[34, 56, 78],
       [87, 65, 43],
       [55, 77, 33]])

In [104]:
s.ndim

1

In [80]:
s.itemsize

4

In [81]:
s.size

9

In [83]:
s.shape

(3, 3)

In [84]:
s.dtype

dtype('int32')

In [85]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [86]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
np.arange(2,5)

array([2, 3, 4])

In [88]:
s = np.arange(15)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [89]:
s.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [105]:
s.ndim

1

In [90]:
s.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [91]:
s.reshape(5,4)  # kindly put those value which are factor on 15

ValueError: cannot reshape array of size 15 into shape (5,4)

In [92]:
j = np.arange(12)
j

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [94]:
j.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
j.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [106]:
k =np.arange(35)
k.reshape(5,7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [107]:
k.ndim   # ndim is no of dimensions

1

In [108]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [110]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [111]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Broadcasting in Numpy

In [112]:
a = np.array([1.0,2.0,3.0])
b = np.array([2.0,2.0,2.0])
a*b

array([2., 4., 6.])

In [113]:
a = np.array([1.0,2.0,3.0])
b=2.0
a*b

array([2., 4., 6.])

In [144]:
a = np.array([20,30,40,50])
b = np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [117]:
s = np.array([1,2,3])
k = np.array([2,3,4])
s*k

array([ 2,  6, 12])

In [118]:
s+k

array([3, 5, 7])

In [119]:
b = np.random.random([2,3])
b

array([[0.52013316, 0.64586983, 0.26901026],
       [0.01511717, 0.39680551, 0.63898749]])

In [121]:
c = np.ones([2,3])
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [122]:
d = b+c
d

array([[1.52013316, 1.64586983, 1.26901026],
       [1.01511717, 1.39680551, 1.63898749]])

Universal Functions

In [125]:
B = np.arange(3)
B

array([0, 1, 2])

In [126]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [127]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [128]:
c = np.array([2,1,4])
np.add(B,c)

array([2, 2, 6])

Indexing, Slicing and Iterating

In [129]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
a[2]

2

In [131]:
a[2:5]

array([2, 3, 4])

In [132]:
a[-1]

9

In [133]:
a[-2]

8

In [134]:
a[-3]

7

In [135]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
a[-4:]

array([6, 7, 8, 9])

In [137]:
a[-4:-2]

array([6, 7])

In [139]:
d2 = np.arange(20)
d2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [140]:
d2[5:]  # Slicing from 5th index till end of the array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [141]:
d3 = np.array([np.nan,1,2,3,np.nan,6,7,8])    # nan is use for missing data i donn't have any information that's why we use nan 
d3

array([nan,  1.,  2.,  3., nan,  6.,  7.,  8.])

The random module provides nice funtions to generate random numbers (and also statistical distributions) of 
                                                     any given shape.rand function will generate any number between 0 and 1)

In [142]:
np.random.rand(2,2)  # uniform distributions ----> similar like random

array([[0.84530189, 0.71971689],
       [0.30174892, 0.15485849]])

Random will generate any number for normal distribution in the given dimension format

In [146]:
np.random.randn(2,3)   # random and rand they are generating positive no but randn is generating some positive and some negative no.

array([[ 0.96843032,  1.30324274, -0.33998354],
       [ 1.23365876, -0.13486068,  0.781399  ]])